-- Reset operational/test data without deleting user accounts or access configuration.
-- Only the CEO and Administrator may run this function. The function is atomic:
-- if any delete fails, PostgreSQL rolls the whole reset back.
CREATE OR REPLACE FUNCTION public.reset_test_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL
     OR NOT (
       public.has_role(auth.uid(), 'ceo'::public.app_role)
       OR public.has_role(auth.uid(), 'administrator'::public.app_role)
     ) THEN
    RAISE EXCEPTION 'Only the CEO or Administrator can reset test data';
  END IF;

  -- Delete dependent/transactional records first to satisfy foreign keys.
  DELETE FROM public.record_change_requests WHERE id IS NOT NULL;
  DELETE FROM public.batch_movements WHERE id IS NOT NULL;
  DELETE FROM public.sale_items WHERE id IS NOT NULL;
  DELETE FROM public.sales WHERE id IS NOT NULL;
  DELETE FROM public.inventory_transactions WHERE id IS NOT NULL;
  DELETE FROM public.inventory_items WHERE id IS NOT NULL;
  -- Approvals reference expenses, so remove them before deleting expenses.
  DELETE FROM public.executive_approvals WHERE id IS NOT NULL;
  DELETE FROM public.expenses WHERE id IS NOT NULL;
  DELETE FROM public.income WHERE id IS NOT NULL;
  DELETE FROM public.animals WHERE id IS NOT NULL;
  DELETE FROM public.animal_batches WHERE id IS NOT NULL;
  DELETE FROM public.customers WHERE id IS NOT NULL;
  DELETE FROM public.suppliers WHERE id IS NOT NULL;
  DELETE FROM public.employees WHERE id IS NOT NULL;
  DELETE FROM public.documents WHERE id IS NOT NULL;
  DELETE FROM public.notifications WHERE id IS NOT NULL;
  DELETE FROM public.secretary_visitors WHERE id IS NOT NULL;
  DELETE FROM public.secretary_correspondence WHERE id IS NOT NULL;
  DELETE FROM public.secretary_meetings WHERE id IS NOT NULL;

  -- Clear setup records commonly created during testing while retaining the
  -- farm's official profile, livestock types, user accounts and permissions.
  DELETE FROM public.breeds WHERE id IS NOT NULL;
  DELETE FROM public.farm_sections WHERE id IS NOT NULL;

  -- Remove audit entries generated by the deletes above as well.
  DELETE FROM public.activity_logs WHERE id IS NOT NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.reset_test_data() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reset_test_data() TO authenticated;
