-- Reset operational/test data without deleting user accounts or access configuration.
-- Only the CEO and Administrator may run this function. The function is atomic:
-- if any delete fails, PostgreSQL rolls the whole reset back.
CREATE OR REPLACE FUNCTION public.reset_test_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL
     OR NOT (
       public.has_role(auth.uid(), 'ceo'::public.app_role)
       OR public.has_role(auth.uid(), 'administrator'::public.app_role)
     ) THEN
    RAISE EXCEPTION 'Only the CEO or Administrator can reset test data';
  END IF;

  -- Delete dependent/transactional records first to satisfy foreign keys.
  DELETE FROM public.record_change_requests WHERE true;
  DELETE FROM public.batch_movements WHERE true;
  DELETE FROM public.sale_items WHERE true;
  DELETE FROM public.sales WHERE true;
  DELETE FROM public.inventory_transactions WHERE true;
  DELETE FROM public.inventory_items WHERE true;
  DELETE FROM public.expenses WHERE true;
  DELETE FROM public.income WHERE true;
  DELETE FROM public.animals WHERE true;
  DELETE FROM public.animal_batches WHERE true;
  DELETE FROM public.customers WHERE true;
  DELETE FROM public.suppliers WHERE true;
  DELETE FROM public.employees WHERE true;
  DELETE FROM public.documents WHERE true;
  DELETE FROM public.notifications WHERE true;
  DELETE FROM public.secretary_visitors WHERE true;
  DELETE FROM public.secretary_correspondence WHERE true;
  DELETE FROM public.secretary_meetings WHERE true;

  -- Clear setup records commonly created during testing while retaining the
  -- farm's official profile, livestock types, user accounts and permissions.
  DELETE FROM public.breeds WHERE true;
  DELETE FROM public.farm_sections WHERE true;

  -- Remove audit entries generated by the deletes above as well.
  DELETE FROM public.activity_logs WHERE true;
END;
$$;

REVOKE ALL ON FUNCTION public.reset_test_data() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reset_test_data() TO authenticated;
