-- Reset operational/test data without deleting user accounts or access configuration.
-- Only the CEO and Administrator may run this function. The function is atomic:
-- if any delete fails, PostgreSQL rolls the whole reset back.
CREATE OR REPLACE FUNCTION public.reset_test_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL
     OR NOT (
       public.has_role(auth.uid(), 'ceo'::public.app_role)
       OR public.has_role(auth.uid(), 'administrator'::public.app_role)
     ) THEN
    RAISE EXCEPTION 'Only the CEO or Administrator can reset test data';
  END IF;

  -- Delete dependent/transactional records first to satisfy foreign keys.
  DELETE FROM public.record_change_requests;
  DELETE FROM public.batch_movements;
  DELETE FROM public.sale_items;
  DELETE FROM public.sales;
  DELETE FROM public.inventory_transactions;
  DELETE FROM public.inventory_items;
  DELETE FROM public.expenses;
  DELETE FROM public.income;
  DELETE FROM public.animals;
  DELETE FROM public.animal_batches;
  DELETE FROM public.customers;
  DELETE FROM public.suppliers;
  DELETE FROM public.employees;
  DELETE FROM public.documents;
  DELETE FROM public.notifications;
  DELETE FROM public.secretary_visitors;
  DELETE FROM public.secretary_correspondence;
  DELETE FROM public.secretary_meetings;

  -- Clear setup records commonly created during testing while retaining the
  -- farm's official profile, livestock types, user accounts and permissions.
  DELETE FROM public.breeds;
  DELETE FROM public.farm_sections;

  -- Remove audit entries generated by the deletes above as well.
  DELETE FROM public.activity_logs;
END;
$$;

REVOKE ALL ON FUNCTION public.reset_test_data() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reset_test_data() TO authenticated;
